### PR TITLE
Resolve version ranges

### PR DESCRIPTION
**Pull request by asymmetric**
Always takes the highest version in a range. A single version is also treated as a range.

Tried it with a 

```nix
with import <nixpkgs> { };

(buildMaven ./project-info.json).build
```

but it still complained about missing `url` fields.

Do you know of a quick way to query the huge JSON object to find missing `url`s?

### CODE REVIEW

**Comment by asymmetric** [comment]
Love it, the one without `url` is k :joy:

```json
    {
      "artifactId": "parent",
      "groupId": "com.runtimeverification.k",
      "version": "1.0-SNAPSHOT",
      "classifier": "",
      "extension": "pom",
      "dependencies": [
         // ...
      ]
    },
```

**Comment by asymmetric** [comment]
Ah I see, it's because of [this line](https://github.com/ttuegel/mvn2nix-maven-plugin/blob/resolve-local-to-remote-repository/src/main/java/org/nixos/mvn2nix/Mvn2NixMojo.java#L479).

I suppose we could somehow infer the URL from the `pom.xml`, but what repo should we use? The only approaches that come to mind are either:

* take the first in the list of declared repos
* hardcode to central

Neither seems very good. Ideas?

**Comment by asymmetric** [comment]
On second look, I see why `WorkspaceRepository` is a noop - it doesn't make sense to try to fetch them, they're not a dependency, they're part of the checkout.

I wonder though why something with `artifactId = parent` ended up being resolved though.

**Comment by asymmetric** [comment]
There's another entry for `parent`:


```json
    {
      "artifactId": "parent",
      "groupId": "com.runtimeverification.rv_match",
      "version": "1.0-20180731.063211-125",
      "classifier": "",
      "extension": "pom",
      "dependencies": [],
      "unresolved-version": "1.0-SNAPSHOT",
      "repository-id": "runtime.verification.snapshots",
      "metadata": {
        "url": "https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/maven-metadata.xml",
        "sha1": "ba70f88b19722184b7b6584f298eaa6c94dbb8ad"
      },
      "authenticated": false,
      "url": "https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/parent-1.0-20180731.063211-125.pom",
      "sha1": "7e9ed2796d455f0380b6720927cf764f3b7e6833",
      "relocations": []
    },
```

This one is a remote artifact, and it does have a `url`.

**Comment by asymmetric** [comment]
I think the problem is that `gen` is being written to before the check for `WorkspaceRepository`, so the `//Do nothing` is not actually true.

**Comment by asymmetric** [comment]
Looks good! It's trying to build the world so it'll take a while, but the `project-info.json` is now valid! :tada:

**Comment by asymmetric** [comment]
```shell
asymmetric@tachikoma:~/code/dapphub/k$ mvn -o --settings /nix/store/6jdcbcgq3lzjvnhgcmljsirxwlqzd8z4-settings.xml compile -e                                                         [129/9115]
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.springframework.build:aws-maven:5.0.0.RELEASE or one of its dependencies could not be resolved: Failed to collect dependencies at org.springf
ramework.build:aws-maven:jar:5.0.0.RELEASE -> com.amazonaws:aws-java-sdk:jar:1.7.1 -> joda-time:joda-time:jar:[2.2,) @
 @
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.springframework.build:aws-maven:5.0.0.RELEASE or one of its dependencies could not be resolved: Failed to collect dependencies at org.springf
ramework.build:aws-maven:jar:5.0.0.RELEASE -> com.amazonaws:aws-java-sdk:jar:1.7.1 -> joda-time:joda-time:jar:[2.2,) @
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:383)
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:397)
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:388)
    at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:81)
    at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by asymmetric** [comment]
I'm not sure where this version range for `joda-time` is coming from - it's not in the `project-info.json` as of 6725599.

For the record, it's not a matter of how we resolve the version range: I've tried both lowest and highest, it fails in both cases.

**Comment by asymmetric** [comment]
I've tried removing `aws-maven` from the top `pom.xml`, but it nevertheless ended up as a requirement of `k` in the `project-json.info`. Looking at the output of running `mvn2nix`, you can see how it's downloading the `pom` for `k` from a repo instead of using the local one:

```shell
asymmetric@tachikoma:~/code/dapphub/k$ mvn -Dmaven.repo.local=$(mktemp -d -t mavenXXX) org.nixos.mvn2nix:mvn2nix-maven-plugin:mvn2nix
[INFO] Scanning for projects...
Downloading from runtime.verification.snapshots: https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/maven-metadata.xm
l
Downloaded from runtime.verification.snapshots: https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/maven-metadata.xml
 (615 B at 643 B/s)
Downloading from runtime.verification.snapshots: https://s3.amazonaws.com/repo.runtime.verification/repository/snapshots/com/runtimeverification/rv_match/parent/1.0-SNAPSHOT/parent-1.0-201808
01.065217-127.pom
```

I wonder

a) if this behaviour is desirable
b) if we are somehow missing to do version range resolution in this case

**Comment by asymmetric** [comment]
[This](https://repo1.maven.org/maven2/com/emc/vipr/aws-java-sdk/1.7.5/aws-java-sdk-1.7.5.pom) is the POM for the package that requires `joda-time` with the version range.

Considering that the `pom.xml` for `joda-time` says: `<!-- Build does not work on Java 9 or later as Java 5 is not a valid target -->`, and that newer versions of `aws-java-sdk` don't use it anymore, and that the POM for `aws-maven` says:

```xml
<dependency>
<groupId>com.amazonaws</groupId>
<artifactId>aws-java-sdk</artifactId>
<version>${amazonaws.version}</version>
```

would it be possible to bump `aws-java-sdk` and see if this fixes the issue? This would not be a proper solution to our problem maybe, since the `joda-time:2.2` pom does not have that warning and still does not build, but maybe it gets us closer to a working build.

/cc @ehildenb

**Comment by ehildenb** [comment]
We can certainly try bumping a version number as a PR into K, though I'm not sure of (1) how versioning in java or maven works, and (2) which version number you want me to bump (the version number for K)?

I remember that about a year ago, or 8 months ago, there was a big fiasco where the version number was bumped prematurely for a while, then rolled back. Maybe it has something to do with that?

**Comment by asymmetric** [comment]
The dependency chain is `org.springframework.build:aws-maven:jar:5.0.0.RELEASE -> com.amazonaws:aws-java-sdk:jar:1.7.1 -> joda-time:joda-time:jar:[2.2,)`.

`aws-maven:jar:5.0.0.RELEASE` is the latest, so in case it's possible, the idea would be to bump `aws-java-sdk` to latest, so that the dependency to `joda-time` is dropped.

This might be a temporary fix, or maybe not even that, in case there are other transitive dependencies of build extensions that use version ranges.

We should figure a way out to solve that too.

**Comment by asymmetric** [comment]
Another approach to getting rid of `joda-time` is switching out `aws-maven` with this [updated fork](https://mvnrepository.com/artifact/org.zalando.org.springframework.build/aws-maven), which doesn't have a transitive dependency on it.

I suppose this would have to be done on all the K `pom.xml`s, and on `rv_match` as well, since it's declared as a `parent`.

**Comment by ttuegel** [comment]
For some reason, GitHub was not sending me notifications about this repository, so I just discovered this pull request. Sorry!

I think your approach to use the latest version in the range is reasonable. We should also stop emitting entries into `project-info.json` for `WorkspaceRepository` dependencies.

By the way, it should no longer be necessary to do `-Dmaven.repo.local`. In fact, if you are trying to test local modifications to `mvn2nix-maven-plugin`, then resetting the local repository path won't work.

**Comment by asymmetric** [comment]
> We should also stop emitting entries into project-info.json for WorkspaceRepository dependencies.

We don't anymore since efe634d2b30db24693754870246bd84e50bdce69

> By the way, it should no longer be necessary to do -Dmaven.repo.local. In fact, if you are trying to test local modifications to mvn2nix-maven-plugin, then resetting the local repository path won't work.

Yeah sorry, that was just a mistake in the snippet I posted, I'm actually running a vanilla `mvn2nix` invocation.

**Comment by asymmetric** [comment]
K has merged [my PR](https://github.com/kframework/k/commit/c14f5ff8be7afd0705d20c43ecd0bdaa11c9e090) updating the `aws-maven` version.

AFAICT the same needs to be done on `rv_match`, but that's a private repo.

**Comment by ttuegel** [comment]
> AFAICT the same needs to be done on rv_match, but that's a private repo.

I may be able to help with that in a moment...

**Pull request merged**
